[package]
name = "metaboss_lib"
version = "0.0.0"
edition = "2021"
description = "The core library for the metaboss cli."
repository = "https://github.com/samuelvanderwaal/metaboss_lib"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
metaplex-token-metadata = "0.0.1"
solana-account-decoder = "1.9.1"
solana-client = "1.9.1"
solana-program = "1.9.1"
solana-sdk = "1.9.1"
thiserror = "1.0.30"

[features]
